volumes:
  redis-volume:
  redis-gui-volume:
networks:
  web_api:
    driver: bridgeA

services:
# ----------------------------------------------------------------------------------------------------------------------
# databases
  redis:
    image: redis:7.0.8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    restart: always
    networks:
      - web_api
# ----------------------------------------------------------------------------------------------------------------------
# tools
  redis-gui:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    depends_on:
      - redis
    volumes:
      - redis-gui-volume:/db

