// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	ExerciseCategories string
	Exercises          string
	TrainingRecords    string
	TrainingSetDetails string
	TrainingSets       string
	Users              string
}{
	ExerciseCategories: "exercise_categories",
	Exercises:          "exercises",
	TrainingRecords:    "training_records",
	TrainingSetDetails: "training_set_details",
	TrainingSets:       "training_sets",
	Users:              "users",
}
