// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Exercise is an object representing the database table.
type Exercise struct { // 種目ID
	ID int `boil:"id" json:"id" toml:"id" yaml:"id"`
	// 種目名
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`
	// 種目の説明
	Description null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	// ユーザーID
	UserID int `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	// カテゴリーID
	CategoryID int `boil:"category_id" json:"category_id" toml:"category_id" yaml:"category_id"`
	// レコード作成日時
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	// レコード更新日時
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	// レコード削除日時
	DeletedAt null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *exerciseR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L exerciseL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ExerciseColumns = struct {
	ID          string
	Name        string
	Description string
	UserID      string
	CategoryID  string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   string
}{
	ID:          "id",
	Name:        "name",
	Description: "description",
	UserID:      "user_id",
	CategoryID:  "category_id",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

var ExerciseTableColumns = struct {
	ID          string
	Name        string
	Description string
	UserID      string
	CategoryID  string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   string
}{
	ID:          "exercises.id",
	Name:        "exercises.name",
	Description: "exercises.description",
	UserID:      "exercises.user_id",
	CategoryID:  "exercises.category_id",
	CreatedAt:   "exercises.created_at",
	UpdatedAt:   "exercises.updated_at",
	DeletedAt:   "exercises.deleted_at",
}

// Generated where

var ExerciseWhere = struct {
	ID          whereHelperint
	Name        whereHelperstring
	Description whereHelpernull_String
	UserID      whereHelperint
	CategoryID  whereHelperint
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
	DeletedAt   whereHelpernull_Time
}{
	ID:          whereHelperint{field: "`exercises`.`id`"},
	Name:        whereHelperstring{field: "`exercises`.`name`"},
	Description: whereHelpernull_String{field: "`exercises`.`description`"},
	UserID:      whereHelperint{field: "`exercises`.`user_id`"},
	CategoryID:  whereHelperint{field: "`exercises`.`category_id`"},
	CreatedAt:   whereHelpertime_Time{field: "`exercises`.`created_at`"},
	UpdatedAt:   whereHelpertime_Time{field: "`exercises`.`updated_at`"},
	DeletedAt:   whereHelpernull_Time{field: "`exercises`.`deleted_at`"},
}

// ExerciseRels is where relationship names are stored.
var ExerciseRels = struct {
	User         string
	Category     string
	TrainingSets string
}{
	User:         "User",
	Category:     "Category",
	TrainingSets: "TrainingSets",
}

// exerciseR is where relationships are stored.
type exerciseR struct {
	User         *User             `boil:"User" json:"User" toml:"User" yaml:"User"`
	Category     *ExerciseCategory `boil:"Category" json:"Category" toml:"Category" yaml:"Category"`
	TrainingSets TrainingSetSlice  `boil:"TrainingSets" json:"TrainingSets" toml:"TrainingSets" yaml:"TrainingSets"`
}

// NewStruct creates a new relationship struct
func (*exerciseR) NewStruct() *exerciseR {
	return &exerciseR{}
}

func (r *exerciseR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

func (r *exerciseR) GetCategory() *ExerciseCategory {
	if r == nil {
		return nil
	}
	return r.Category
}

func (r *exerciseR) GetTrainingSets() TrainingSetSlice {
	if r == nil {
		return nil
	}
	return r.TrainingSets
}

// exerciseL is where Load methods for each relationship are stored.
type exerciseL struct{}

var (
	exerciseAllColumns            = []string{"id", "name", "description", "user_id", "category_id", "created_at", "updated_at", "deleted_at"}
	exerciseColumnsWithoutDefault = []string{"name", "description", "user_id", "category_id", "deleted_at"}
	exerciseColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	exercisePrimaryKeyColumns     = []string{"id"}
	exerciseGeneratedColumns      = []string{}
)

type (
	// ExerciseSlice is an alias for a slice of pointers to Exercise.
	// This should almost always be used instead of []Exercise.
	ExerciseSlice []*Exercise
	// ExerciseHook is the signature for custom Exercise hook methods
	ExerciseHook func(context.Context, boil.ContextExecutor, *Exercise) error

	exerciseQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	exerciseType                 = reflect.TypeOf(&Exercise{})
	exerciseMapping              = queries.MakeStructMapping(exerciseType)
	exercisePrimaryKeyMapping, _ = queries.BindMapping(exerciseType, exerciseMapping, exercisePrimaryKeyColumns)
	exerciseInsertCacheMut       sync.RWMutex
	exerciseInsertCache          = make(map[string]insertCache)
	exerciseUpdateCacheMut       sync.RWMutex
	exerciseUpdateCache          = make(map[string]updateCache)
	exerciseUpsertCacheMut       sync.RWMutex
	exerciseUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var exerciseAfterSelectHooks []ExerciseHook

var exerciseBeforeInsertHooks []ExerciseHook
var exerciseAfterInsertHooks []ExerciseHook

var exerciseBeforeUpdateHooks []ExerciseHook
var exerciseAfterUpdateHooks []ExerciseHook

var exerciseBeforeDeleteHooks []ExerciseHook
var exerciseAfterDeleteHooks []ExerciseHook

var exerciseBeforeUpsertHooks []ExerciseHook
var exerciseAfterUpsertHooks []ExerciseHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Exercise) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exerciseAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Exercise) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exerciseBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Exercise) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exerciseAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Exercise) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exerciseBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Exercise) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exerciseAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Exercise) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exerciseBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Exercise) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exerciseAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Exercise) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exerciseBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Exercise) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exerciseAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddExerciseHook registers your hook function for all future operations.
func AddExerciseHook(hookPoint boil.HookPoint, exerciseHook ExerciseHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		exerciseAfterSelectHooks = append(exerciseAfterSelectHooks, exerciseHook)
	case boil.BeforeInsertHook:
		exerciseBeforeInsertHooks = append(exerciseBeforeInsertHooks, exerciseHook)
	case boil.AfterInsertHook:
		exerciseAfterInsertHooks = append(exerciseAfterInsertHooks, exerciseHook)
	case boil.BeforeUpdateHook:
		exerciseBeforeUpdateHooks = append(exerciseBeforeUpdateHooks, exerciseHook)
	case boil.AfterUpdateHook:
		exerciseAfterUpdateHooks = append(exerciseAfterUpdateHooks, exerciseHook)
	case boil.BeforeDeleteHook:
		exerciseBeforeDeleteHooks = append(exerciseBeforeDeleteHooks, exerciseHook)
	case boil.AfterDeleteHook:
		exerciseAfterDeleteHooks = append(exerciseAfterDeleteHooks, exerciseHook)
	case boil.BeforeUpsertHook:
		exerciseBeforeUpsertHooks = append(exerciseBeforeUpsertHooks, exerciseHook)
	case boil.AfterUpsertHook:
		exerciseAfterUpsertHooks = append(exerciseAfterUpsertHooks, exerciseHook)
	}
}

// One returns a single exercise record from the query.
func (q exerciseQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Exercise, error) {
	o := &Exercise{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: failed to execute a one query for exercises")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Exercise records from the query.
func (q exerciseQuery) All(ctx context.Context, exec boil.ContextExecutor) (ExerciseSlice, error) {
	var o []*Exercise

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "db: failed to assign all query results to Exercise slice")
	}

	if len(exerciseAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Exercise records in the query.
func (q exerciseQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to count exercises rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q exerciseQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "db: failed to check if exercises exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *Exercise) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Category pointed to by the foreign key.
func (o *Exercise) Category(mods ...qm.QueryMod) exerciseCategoryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.CategoryID),
	}

	queryMods = append(queryMods, mods...)

	return ExerciseCategories(queryMods...)
}

// TrainingSets retrieves all the training_set's TrainingSets with an executor.
func (o *Exercise) TrainingSets(mods ...qm.QueryMod) trainingSetQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`training_sets`.`exercise_id`=?", o.ID),
	)

	return TrainingSets(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (exerciseL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExercise interface{}, mods queries.Applicator) error {
	var slice []*Exercise
	var object *Exercise

	if singular {
		var ok bool
		object, ok = maybeExercise.(*Exercise)
		if !ok {
			object = new(Exercise)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExercise)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExercise))
			}
		}
	} else {
		s, ok := maybeExercise.(*[]*Exercise)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExercise)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExercise))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &exerciseR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &exerciseR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Exercises = append(foreign.R.Exercises, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Exercises = append(foreign.R.Exercises, local)
				break
			}
		}
	}

	return nil
}

// LoadCategory allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (exerciseL) LoadCategory(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExercise interface{}, mods queries.Applicator) error {
	var slice []*Exercise
	var object *Exercise

	if singular {
		var ok bool
		object, ok = maybeExercise.(*Exercise)
		if !ok {
			object = new(Exercise)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExercise)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExercise))
			}
		}
	} else {
		s, ok := maybeExercise.(*[]*Exercise)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExercise)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExercise))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &exerciseR{}
		}
		args = append(args, object.CategoryID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &exerciseR{}
			}

			for _, a := range args {
				if a == obj.CategoryID {
					continue Outer
				}
			}

			args = append(args, obj.CategoryID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`exercise_categories`),
		qm.WhereIn(`exercise_categories.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ExerciseCategory")
	}

	var resultSlice []*ExerciseCategory
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ExerciseCategory")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for exercise_categories")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for exercise_categories")
	}

	if len(exerciseCategoryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Category = foreign
		if foreign.R == nil {
			foreign.R = &exerciseCategoryR{}
		}
		foreign.R.CategoryExercises = append(foreign.R.CategoryExercises, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CategoryID == foreign.ID {
				local.R.Category = foreign
				if foreign.R == nil {
					foreign.R = &exerciseCategoryR{}
				}
				foreign.R.CategoryExercises = append(foreign.R.CategoryExercises, local)
				break
			}
		}
	}

	return nil
}

// LoadTrainingSets allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (exerciseL) LoadTrainingSets(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExercise interface{}, mods queries.Applicator) error {
	var slice []*Exercise
	var object *Exercise

	if singular {
		var ok bool
		object, ok = maybeExercise.(*Exercise)
		if !ok {
			object = new(Exercise)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExercise)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExercise))
			}
		}
	} else {
		s, ok := maybeExercise.(*[]*Exercise)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExercise)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExercise))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &exerciseR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &exerciseR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`training_sets`),
		qm.WhereIn(`training_sets.exercise_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load training_sets")
	}

	var resultSlice []*TrainingSet
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice training_sets")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on training_sets")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for training_sets")
	}

	if len(trainingSetAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TrainingSets = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &trainingSetR{}
			}
			foreign.R.Exercise = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ExerciseID {
				local.R.TrainingSets = append(local.R.TrainingSets, foreign)
				if foreign.R == nil {
					foreign.R = &trainingSetR{}
				}
				foreign.R.Exercise = local
				break
			}
		}
	}

	return nil
}

// SetUser of the exercise to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Exercises.
func (o *Exercise) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `exercises` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"user_id"}),
		strmangle.WhereClause("`", "`", 0, exercisePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &exerciseR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Exercises: ExerciseSlice{o},
		}
	} else {
		related.R.Exercises = append(related.R.Exercises, o)
	}

	return nil
}

// SetCategory of the exercise to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.CategoryExercises.
func (o *Exercise) SetCategory(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ExerciseCategory) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `exercises` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"category_id"}),
		strmangle.WhereClause("`", "`", 0, exercisePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CategoryID = related.ID
	if o.R == nil {
		o.R = &exerciseR{
			Category: related,
		}
	} else {
		o.R.Category = related
	}

	if related.R == nil {
		related.R = &exerciseCategoryR{
			CategoryExercises: ExerciseSlice{o},
		}
	} else {
		related.R.CategoryExercises = append(related.R.CategoryExercises, o)
	}

	return nil
}

// AddTrainingSets adds the given related objects to the existing relationships
// of the exercise, optionally inserting them as new records.
// Appends related to o.R.TrainingSets.
// Sets related.R.Exercise appropriately.
func (o *Exercise) AddTrainingSets(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TrainingSet) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ExerciseID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `training_sets` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"exercise_id"}),
				strmangle.WhereClause("`", "`", 0, trainingSetPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ExerciseID = o.ID
		}
	}

	if o.R == nil {
		o.R = &exerciseR{
			TrainingSets: related,
		}
	} else {
		o.R.TrainingSets = append(o.R.TrainingSets, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &trainingSetR{
				Exercise: o,
			}
		} else {
			rel.R.Exercise = o
		}
	}
	return nil
}

// Exercises retrieves all the records using an executor.
func Exercises(mods ...qm.QueryMod) exerciseQuery {
	mods = append(mods, qm.From("`exercises`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`exercises`.*"})
	}

	return exerciseQuery{q}
}

// FindExercise retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindExercise(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Exercise, error) {
	exerciseObj := &Exercise{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `exercises` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, exerciseObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: unable to select from exercises")
	}

	if err = exerciseObj.doAfterSelectHooks(ctx, exec); err != nil {
		return exerciseObj, err
	}

	return exerciseObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Exercise) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("db: no exercises provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(exerciseColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	exerciseInsertCacheMut.RLock()
	cache, cached := exerciseInsertCache[key]
	exerciseInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			exerciseAllColumns,
			exerciseColumnsWithDefault,
			exerciseColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(exerciseType, exerciseMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(exerciseType, exerciseMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `exercises` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `exercises` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `exercises` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, exercisePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "db: unable to insert into exercises")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == exerciseMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "db: unable to populate default values for exercises")
	}

CacheNoHooks:
	if !cached {
		exerciseInsertCacheMut.Lock()
		exerciseInsertCache[key] = cache
		exerciseInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Exercise.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Exercise) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	exerciseUpdateCacheMut.RLock()
	cache, cached := exerciseUpdateCache[key]
	exerciseUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			exerciseAllColumns,
			exercisePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("db: unable to update exercises, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `exercises` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, exercisePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(exerciseType, exerciseMapping, append(wl, exercisePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update exercises row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by update for exercises")
	}

	if !cached {
		exerciseUpdateCacheMut.Lock()
		exerciseUpdateCache[key] = cache
		exerciseUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q exerciseQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all for exercises")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected for exercises")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ExerciseSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("db: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), exercisePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `exercises` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, exercisePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all in exercise slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected all in update all exercise")
	}
	return rowsAff, nil
}

var mySQLExerciseUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Exercise) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("db: no exercises provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(exerciseColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLExerciseUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	exerciseUpsertCacheMut.RLock()
	cache, cached := exerciseUpsertCache[key]
	exerciseUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			exerciseAllColumns,
			exerciseColumnsWithDefault,
			exerciseColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			exerciseAllColumns,
			exercisePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("db: unable to upsert exercises, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`exercises`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `exercises` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(exerciseType, exerciseMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(exerciseType, exerciseMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "db: unable to upsert for exercises")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == exerciseMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(exerciseType, exerciseMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "db: unable to retrieve unique values for exercises")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "db: unable to populate default values for exercises")
	}

CacheNoHooks:
	if !cached {
		exerciseUpsertCacheMut.Lock()
		exerciseUpsertCache[key] = cache
		exerciseUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Exercise record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Exercise) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("db: no Exercise provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), exercisePrimaryKeyMapping)
	sql := "DELETE FROM `exercises` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete from exercises")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by delete for exercises")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q exerciseQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("db: no exerciseQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from exercises")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for exercises")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ExerciseSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(exerciseBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), exercisePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `exercises` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, exercisePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from exercise slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for exercises")
	}

	if len(exerciseAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Exercise) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindExercise(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ExerciseSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ExerciseSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), exercisePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `exercises`.* FROM `exercises` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, exercisePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "db: unable to reload all in ExerciseSlice")
	}

	*o = slice

	return nil
}

// ExerciseExists checks if the Exercise row exists.
func ExerciseExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `exercises` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "db: unable to check if exercises exists")
	}

	return exists, nil
}

// Exists checks if the Exercise row exists.
func (o *Exercise) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ExerciseExists(ctx, exec, o.ID)
}
