// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// TrainingSet is an object representing the database table.
type TrainingSet struct { // セットID
	ID int `boil:"id" json:"id" toml:"id" yaml:"id"`
	// 記録ID
	TrainingRecordID int `boil:"training_record_id" json:"training_record_id" toml:"training_record_id" yaml:"training_record_id"`
	// 種目ID
	ExerciseID int `boil:"exercise_id" json:"exercise_id" toml:"exercise_id" yaml:"exercise_id"`
	// その他詳細
	Memo null.String `boil:"memo" json:"memo,omitempty" toml:"memo" yaml:"memo,omitempty"`
	// レコード作成日時
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	// レコード更新日時
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	// レコード削除日時
	DeletedAt null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *trainingSetR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L trainingSetL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TrainingSetColumns = struct {
	ID               string
	TrainingRecordID string
	ExerciseID       string
	Memo             string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        string
}{
	ID:               "id",
	TrainingRecordID: "training_record_id",
	ExerciseID:       "exercise_id",
	Memo:             "memo",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
	DeletedAt:        "deleted_at",
}

var TrainingSetTableColumns = struct {
	ID               string
	TrainingRecordID string
	ExerciseID       string
	Memo             string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        string
}{
	ID:               "training_sets.id",
	TrainingRecordID: "training_sets.training_record_id",
	ExerciseID:       "training_sets.exercise_id",
	Memo:             "training_sets.memo",
	CreatedAt:        "training_sets.created_at",
	UpdatedAt:        "training_sets.updated_at",
	DeletedAt:        "training_sets.deleted_at",
}

// Generated where

var TrainingSetWhere = struct {
	ID               whereHelperint
	TrainingRecordID whereHelperint
	ExerciseID       whereHelperint
	Memo             whereHelpernull_String
	CreatedAt        whereHelpertime_Time
	UpdatedAt        whereHelpertime_Time
	DeletedAt        whereHelpernull_Time
}{
	ID:               whereHelperint{field: "`training_sets`.`id`"},
	TrainingRecordID: whereHelperint{field: "`training_sets`.`training_record_id`"},
	ExerciseID:       whereHelperint{field: "`training_sets`.`exercise_id`"},
	Memo:             whereHelpernull_String{field: "`training_sets`.`memo`"},
	CreatedAt:        whereHelpertime_Time{field: "`training_sets`.`created_at`"},
	UpdatedAt:        whereHelpertime_Time{field: "`training_sets`.`updated_at`"},
	DeletedAt:        whereHelpernull_Time{field: "`training_sets`.`deleted_at`"},
}

// TrainingSetRels is where relationship names are stored.
var TrainingSetRels = struct {
	TrainingRecord     string
	Exercise           string
	TrainingSetDetails string
}{
	TrainingRecord:     "TrainingRecord",
	Exercise:           "Exercise",
	TrainingSetDetails: "TrainingSetDetails",
}

// trainingSetR is where relationships are stored.
type trainingSetR struct {
	TrainingRecord     *TrainingRecord        `boil:"TrainingRecord" json:"TrainingRecord" toml:"TrainingRecord" yaml:"TrainingRecord"`
	Exercise           *Exercise              `boil:"Exercise" json:"Exercise" toml:"Exercise" yaml:"Exercise"`
	TrainingSetDetails TrainingSetDetailSlice `boil:"TrainingSetDetails" json:"TrainingSetDetails" toml:"TrainingSetDetails" yaml:"TrainingSetDetails"`
}

// NewStruct creates a new relationship struct
func (*trainingSetR) NewStruct() *trainingSetR {
	return &trainingSetR{}
}

func (r *trainingSetR) GetTrainingRecord() *TrainingRecord {
	if r == nil {
		return nil
	}
	return r.TrainingRecord
}

func (r *trainingSetR) GetExercise() *Exercise {
	if r == nil {
		return nil
	}
	return r.Exercise
}

func (r *trainingSetR) GetTrainingSetDetails() TrainingSetDetailSlice {
	if r == nil {
		return nil
	}
	return r.TrainingSetDetails
}

// trainingSetL is where Load methods for each relationship are stored.
type trainingSetL struct{}

var (
	trainingSetAllColumns            = []string{"id", "training_record_id", "exercise_id", "memo", "created_at", "updated_at", "deleted_at"}
	trainingSetColumnsWithoutDefault = []string{"training_record_id", "exercise_id", "memo", "deleted_at"}
	trainingSetColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	trainingSetPrimaryKeyColumns     = []string{"id"}
	trainingSetGeneratedColumns      = []string{}
)

type (
	// TrainingSetSlice is an alias for a slice of pointers to TrainingSet.
	// This should almost always be used instead of []TrainingSet.
	TrainingSetSlice []*TrainingSet
	// TrainingSetHook is the signature for custom TrainingSet hook methods
	TrainingSetHook func(context.Context, boil.ContextExecutor, *TrainingSet) error

	trainingSetQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	trainingSetType                 = reflect.TypeOf(&TrainingSet{})
	trainingSetMapping              = queries.MakeStructMapping(trainingSetType)
	trainingSetPrimaryKeyMapping, _ = queries.BindMapping(trainingSetType, trainingSetMapping, trainingSetPrimaryKeyColumns)
	trainingSetInsertCacheMut       sync.RWMutex
	trainingSetInsertCache          = make(map[string]insertCache)
	trainingSetUpdateCacheMut       sync.RWMutex
	trainingSetUpdateCache          = make(map[string]updateCache)
	trainingSetUpsertCacheMut       sync.RWMutex
	trainingSetUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var trainingSetAfterSelectHooks []TrainingSetHook

var trainingSetBeforeInsertHooks []TrainingSetHook
var trainingSetAfterInsertHooks []TrainingSetHook

var trainingSetBeforeUpdateHooks []TrainingSetHook
var trainingSetAfterUpdateHooks []TrainingSetHook

var trainingSetBeforeDeleteHooks []TrainingSetHook
var trainingSetAfterDeleteHooks []TrainingSetHook

var trainingSetBeforeUpsertHooks []TrainingSetHook
var trainingSetAfterUpsertHooks []TrainingSetHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TrainingSet) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range trainingSetAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TrainingSet) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range trainingSetBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TrainingSet) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range trainingSetAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TrainingSet) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range trainingSetBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TrainingSet) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range trainingSetAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TrainingSet) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range trainingSetBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TrainingSet) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range trainingSetAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TrainingSet) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range trainingSetBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TrainingSet) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range trainingSetAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTrainingSetHook registers your hook function for all future operations.
func AddTrainingSetHook(hookPoint boil.HookPoint, trainingSetHook TrainingSetHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		trainingSetAfterSelectHooks = append(trainingSetAfterSelectHooks, trainingSetHook)
	case boil.BeforeInsertHook:
		trainingSetBeforeInsertHooks = append(trainingSetBeforeInsertHooks, trainingSetHook)
	case boil.AfterInsertHook:
		trainingSetAfterInsertHooks = append(trainingSetAfterInsertHooks, trainingSetHook)
	case boil.BeforeUpdateHook:
		trainingSetBeforeUpdateHooks = append(trainingSetBeforeUpdateHooks, trainingSetHook)
	case boil.AfterUpdateHook:
		trainingSetAfterUpdateHooks = append(trainingSetAfterUpdateHooks, trainingSetHook)
	case boil.BeforeDeleteHook:
		trainingSetBeforeDeleteHooks = append(trainingSetBeforeDeleteHooks, trainingSetHook)
	case boil.AfterDeleteHook:
		trainingSetAfterDeleteHooks = append(trainingSetAfterDeleteHooks, trainingSetHook)
	case boil.BeforeUpsertHook:
		trainingSetBeforeUpsertHooks = append(trainingSetBeforeUpsertHooks, trainingSetHook)
	case boil.AfterUpsertHook:
		trainingSetAfterUpsertHooks = append(trainingSetAfterUpsertHooks, trainingSetHook)
	}
}

// One returns a single trainingSet record from the query.
func (q trainingSetQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TrainingSet, error) {
	o := &TrainingSet{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: failed to execute a one query for training_sets")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TrainingSet records from the query.
func (q trainingSetQuery) All(ctx context.Context, exec boil.ContextExecutor) (TrainingSetSlice, error) {
	var o []*TrainingSet

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "db: failed to assign all query results to TrainingSet slice")
	}

	if len(trainingSetAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TrainingSet records in the query.
func (q trainingSetQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to count training_sets rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q trainingSetQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "db: failed to check if training_sets exists")
	}

	return count > 0, nil
}

// TrainingRecord pointed to by the foreign key.
func (o *TrainingSet) TrainingRecord(mods ...qm.QueryMod) trainingRecordQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.TrainingRecordID),
	}

	queryMods = append(queryMods, mods...)

	return TrainingRecords(queryMods...)
}

// Exercise pointed to by the foreign key.
func (o *TrainingSet) Exercise(mods ...qm.QueryMod) exerciseQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.ExerciseID),
	}

	queryMods = append(queryMods, mods...)

	return Exercises(queryMods...)
}

// TrainingSetDetails retrieves all the training_set_detail's TrainingSetDetails with an executor.
func (o *TrainingSet) TrainingSetDetails(mods ...qm.QueryMod) trainingSetDetailQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`training_set_details`.`training_set_id`=?", o.ID),
	)

	return TrainingSetDetails(queryMods...)
}

// LoadTrainingRecord allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (trainingSetL) LoadTrainingRecord(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTrainingSet interface{}, mods queries.Applicator) error {
	var slice []*TrainingSet
	var object *TrainingSet

	if singular {
		var ok bool
		object, ok = maybeTrainingSet.(*TrainingSet)
		if !ok {
			object = new(TrainingSet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTrainingSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTrainingSet))
			}
		}
	} else {
		s, ok := maybeTrainingSet.(*[]*TrainingSet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTrainingSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTrainingSet))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &trainingSetR{}
		}
		args = append(args, object.TrainingRecordID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &trainingSetR{}
			}

			for _, a := range args {
				if a == obj.TrainingRecordID {
					continue Outer
				}
			}

			args = append(args, obj.TrainingRecordID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`training_records`),
		qm.WhereIn(`training_records.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TrainingRecord")
	}

	var resultSlice []*TrainingRecord
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TrainingRecord")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for training_records")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for training_records")
	}

	if len(trainingRecordAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.TrainingRecord = foreign
		if foreign.R == nil {
			foreign.R = &trainingRecordR{}
		}
		foreign.R.TrainingSets = append(foreign.R.TrainingSets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TrainingRecordID == foreign.ID {
				local.R.TrainingRecord = foreign
				if foreign.R == nil {
					foreign.R = &trainingRecordR{}
				}
				foreign.R.TrainingSets = append(foreign.R.TrainingSets, local)
				break
			}
		}
	}

	return nil
}

// LoadExercise allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (trainingSetL) LoadExercise(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTrainingSet interface{}, mods queries.Applicator) error {
	var slice []*TrainingSet
	var object *TrainingSet

	if singular {
		var ok bool
		object, ok = maybeTrainingSet.(*TrainingSet)
		if !ok {
			object = new(TrainingSet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTrainingSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTrainingSet))
			}
		}
	} else {
		s, ok := maybeTrainingSet.(*[]*TrainingSet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTrainingSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTrainingSet))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &trainingSetR{}
		}
		args = append(args, object.ExerciseID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &trainingSetR{}
			}

			for _, a := range args {
				if a == obj.ExerciseID {
					continue Outer
				}
			}

			args = append(args, obj.ExerciseID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`exercises`),
		qm.WhereIn(`exercises.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Exercise")
	}

	var resultSlice []*Exercise
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Exercise")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for exercises")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for exercises")
	}

	if len(exerciseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Exercise = foreign
		if foreign.R == nil {
			foreign.R = &exerciseR{}
		}
		foreign.R.TrainingSets = append(foreign.R.TrainingSets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ExerciseID == foreign.ID {
				local.R.Exercise = foreign
				if foreign.R == nil {
					foreign.R = &exerciseR{}
				}
				foreign.R.TrainingSets = append(foreign.R.TrainingSets, local)
				break
			}
		}
	}

	return nil
}

// LoadTrainingSetDetails allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (trainingSetL) LoadTrainingSetDetails(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTrainingSet interface{}, mods queries.Applicator) error {
	var slice []*TrainingSet
	var object *TrainingSet

	if singular {
		var ok bool
		object, ok = maybeTrainingSet.(*TrainingSet)
		if !ok {
			object = new(TrainingSet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTrainingSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTrainingSet))
			}
		}
	} else {
		s, ok := maybeTrainingSet.(*[]*TrainingSet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTrainingSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTrainingSet))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &trainingSetR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &trainingSetR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`training_set_details`),
		qm.WhereIn(`training_set_details.training_set_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load training_set_details")
	}

	var resultSlice []*TrainingSetDetail
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice training_set_details")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on training_set_details")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for training_set_details")
	}

	if len(trainingSetDetailAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TrainingSetDetails = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &trainingSetDetailR{}
			}
			foreign.R.TrainingSet = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.TrainingSetID {
				local.R.TrainingSetDetails = append(local.R.TrainingSetDetails, foreign)
				if foreign.R == nil {
					foreign.R = &trainingSetDetailR{}
				}
				foreign.R.TrainingSet = local
				break
			}
		}
	}

	return nil
}

// SetTrainingRecord of the trainingSet to the related item.
// Sets o.R.TrainingRecord to related.
// Adds o to related.R.TrainingSets.
func (o *TrainingSet) SetTrainingRecord(ctx context.Context, exec boil.ContextExecutor, insert bool, related *TrainingRecord) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `training_sets` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"training_record_id"}),
		strmangle.WhereClause("`", "`", 0, trainingSetPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TrainingRecordID = related.ID
	if o.R == nil {
		o.R = &trainingSetR{
			TrainingRecord: related,
		}
	} else {
		o.R.TrainingRecord = related
	}

	if related.R == nil {
		related.R = &trainingRecordR{
			TrainingSets: TrainingSetSlice{o},
		}
	} else {
		related.R.TrainingSets = append(related.R.TrainingSets, o)
	}

	return nil
}

// SetExercise of the trainingSet to the related item.
// Sets o.R.Exercise to related.
// Adds o to related.R.TrainingSets.
func (o *TrainingSet) SetExercise(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Exercise) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `training_sets` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"exercise_id"}),
		strmangle.WhereClause("`", "`", 0, trainingSetPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ExerciseID = related.ID
	if o.R == nil {
		o.R = &trainingSetR{
			Exercise: related,
		}
	} else {
		o.R.Exercise = related
	}

	if related.R == nil {
		related.R = &exerciseR{
			TrainingSets: TrainingSetSlice{o},
		}
	} else {
		related.R.TrainingSets = append(related.R.TrainingSets, o)
	}

	return nil
}

// AddTrainingSetDetails adds the given related objects to the existing relationships
// of the training_set, optionally inserting them as new records.
// Appends related to o.R.TrainingSetDetails.
// Sets related.R.TrainingSet appropriately.
func (o *TrainingSet) AddTrainingSetDetails(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TrainingSetDetail) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TrainingSetID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `training_set_details` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"training_set_id"}),
				strmangle.WhereClause("`", "`", 0, trainingSetDetailPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TrainingSetID = o.ID
		}
	}

	if o.R == nil {
		o.R = &trainingSetR{
			TrainingSetDetails: related,
		}
	} else {
		o.R.TrainingSetDetails = append(o.R.TrainingSetDetails, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &trainingSetDetailR{
				TrainingSet: o,
			}
		} else {
			rel.R.TrainingSet = o
		}
	}
	return nil
}

// TrainingSets retrieves all the records using an executor.
func TrainingSets(mods ...qm.QueryMod) trainingSetQuery {
	mods = append(mods, qm.From("`training_sets`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`training_sets`.*"})
	}

	return trainingSetQuery{q}
}

// FindTrainingSet retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTrainingSet(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*TrainingSet, error) {
	trainingSetObj := &TrainingSet{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `training_sets` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, trainingSetObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: unable to select from training_sets")
	}

	if err = trainingSetObj.doAfterSelectHooks(ctx, exec); err != nil {
		return trainingSetObj, err
	}

	return trainingSetObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TrainingSet) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("db: no training_sets provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(trainingSetColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	trainingSetInsertCacheMut.RLock()
	cache, cached := trainingSetInsertCache[key]
	trainingSetInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			trainingSetAllColumns,
			trainingSetColumnsWithDefault,
			trainingSetColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(trainingSetType, trainingSetMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(trainingSetType, trainingSetMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `training_sets` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `training_sets` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `training_sets` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, trainingSetPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "db: unable to insert into training_sets")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == trainingSetMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "db: unable to populate default values for training_sets")
	}

CacheNoHooks:
	if !cached {
		trainingSetInsertCacheMut.Lock()
		trainingSetInsertCache[key] = cache
		trainingSetInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TrainingSet.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TrainingSet) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	trainingSetUpdateCacheMut.RLock()
	cache, cached := trainingSetUpdateCache[key]
	trainingSetUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			trainingSetAllColumns,
			trainingSetPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("db: unable to update training_sets, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `training_sets` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, trainingSetPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(trainingSetType, trainingSetMapping, append(wl, trainingSetPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update training_sets row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by update for training_sets")
	}

	if !cached {
		trainingSetUpdateCacheMut.Lock()
		trainingSetUpdateCache[key] = cache
		trainingSetUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q trainingSetQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all for training_sets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected for training_sets")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TrainingSetSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("db: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), trainingSetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `training_sets` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, trainingSetPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all in trainingSet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected all in update all trainingSet")
	}
	return rowsAff, nil
}

var mySQLTrainingSetUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TrainingSet) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("db: no training_sets provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(trainingSetColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLTrainingSetUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	trainingSetUpsertCacheMut.RLock()
	cache, cached := trainingSetUpsertCache[key]
	trainingSetUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			trainingSetAllColumns,
			trainingSetColumnsWithDefault,
			trainingSetColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			trainingSetAllColumns,
			trainingSetPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("db: unable to upsert training_sets, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`training_sets`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `training_sets` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(trainingSetType, trainingSetMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(trainingSetType, trainingSetMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "db: unable to upsert for training_sets")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == trainingSetMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(trainingSetType, trainingSetMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "db: unable to retrieve unique values for training_sets")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "db: unable to populate default values for training_sets")
	}

CacheNoHooks:
	if !cached {
		trainingSetUpsertCacheMut.Lock()
		trainingSetUpsertCache[key] = cache
		trainingSetUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TrainingSet record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TrainingSet) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("db: no TrainingSet provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), trainingSetPrimaryKeyMapping)
	sql := "DELETE FROM `training_sets` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete from training_sets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by delete for training_sets")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q trainingSetQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("db: no trainingSetQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from training_sets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for training_sets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TrainingSetSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(trainingSetBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), trainingSetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `training_sets` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, trainingSetPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from trainingSet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for training_sets")
	}

	if len(trainingSetAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TrainingSet) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTrainingSet(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TrainingSetSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TrainingSetSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), trainingSetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `training_sets`.* FROM `training_sets` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, trainingSetPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "db: unable to reload all in TrainingSetSlice")
	}

	*o = slice

	return nil
}

// TrainingSetExists checks if the TrainingSet row exists.
func TrainingSetExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `training_sets` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "db: unable to check if training_sets exists")
	}

	return exists, nil
}

// Exists checks if the TrainingSet row exists.
func (o *TrainingSet) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TrainingSetExists(ctx, exec, o.ID)
}
